# Generated by Django 3.2.13 on 2023-09-07 02:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CuidadosDicas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuidados', models.CharField(max_length=50)),
                ('lugares_para_ter_cuidado', models.CharField(max_length=20)),
                ('perigo', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('frequencia', models.CharField(choices=[('N', 'Never'), ('S', 'Sometimes'), ('A', 'Always')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='PontosTuristicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ponto_turistico', models.CharField(max_length=50)),
                ('bairro', models.CharField(max_length=20)),
                ('cidade', models.CharField(max_length=20)),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
            ],
        ),
    ]
