# Generated by Django 3.2.13 on 2023-10-30 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdobruno', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuidadosdicas',
            name='frequencia',
        ),
        migrations.AlterField(
            model_name='cuidadosdicas',
            name='cuidados',
            field=models.CharField(max_length=100),
        ),
    ]
